// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtdgxjoerhrbvktcatoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0ZGd4am9lcmhyYnZrdGNhdG9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjE2NDUsImV4cCI6MjA2NTQ5NzY0NX0.S-nikdOEyzMGni9AybMl6yvAb7Me2r_rX9DAw_TDeps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);